services:
  - type: web
    name: asase-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn asase_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asase-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false

databases:
  - name: asase-postgres
    databaseName: asase_db
    user: asase_user
    plan: free
